In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [3]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
one_hot("amazing restaurant", 30)

[8, 18]

In [6]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[26, 7], [8, 18], [16, 12], [8, 2, 8], [24, 8, 16], [6, 7], [23, 8, 17], [14, 5], [14, 24], [9, 22]]


In [7]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[26  7  0  0]
 [ 8 18  0  0]
 [16 12  0  0]
 [ 8  2  8  0]
 [24  8 16  0]
 [ 6  7  0  0]
 [23  8 17  0]
 [14  5  0  0]
 [14 24  0  0]
 [ 9 22  0  0]]


In [9]:
embedded_vector_size = 5

In [10]:
model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [11]:
X = padded_reviews
y = sentiment

In [12]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [14]:
model.fit(X, y, epochs=50, verbose=0)

In [15]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 189ms/step - loss: 0.5520 - accuracy: 1.0000


1.0

In [16]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [18]:
weights[13]

array([-9.3042850e-05,  1.3348307e-02,  3.4388173e-02, -2.2563351e-02,
        2.7398828e-02], dtype=float32)