In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("./sonar_dataset.csv", header=None)
df.sample(5)

0       1       2       3       4       5       6       7       8   \
43   0.0093  0.0269  0.0217  0.0339  0.0305  0.1172  0.1450  0.0638  0.0740   
88   0.0274  0.0242  0.0621  0.0560  0.1129  0.0973  0.1823  0.1745  0.1440   
24   0.0293  0.0644  0.0390  0.0173  0.0476  0.0816  0.0993  0.0315  0.0736   
108  0.0599  0.0474  0.0498  0.0387  0.1026  0.0773  0.0853  0.0447  0.1094   
42   0.0211  0.0319  0.0415  0.0286  0.0121  0.0438  0.1299  0.1390  0.0695   

         9   ...      51      52      53      54      55      56      57  \
43   0.1360  ...  0.0212  0.0091  0.0056  0.0086  0.0092  0.0070  0.0116   
88   0.1808  ...  0.0113  0.0108  0.0085  0.0047  0.0074  0.0104  0.0161   
24   0.0860  ...  0.0035  0.0052  0.0083  0.0078  0.0075  0.0105  0.0160   
108  0.0351  ...  0.0013  0.0005  0.0227  0.0209  0.0081  0.0117  0.0114   
42   0.0568  ...  0.0090  0.0042  0.0153  0.0106  0.0020  0.0105  0.0049   

         58      59  60  
43   0.0060  0.0110   R  
88   0.0220  0.0173   R  
24   0.0095  0.0011   R  
108  0.0112  0.0100   M  
42   0.0070  0.0080   R  

[5 rows x 61 columns]

In [4]:
df.shape

(208, 61)

In [5]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [6]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [8]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [10]:
X = df.drop(60, axis = 1)
y = df[60]
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

In [12]:
y = pd.get_dummies(y, drop_first = True)
y.head()

R
0  1
1  1
2  1
3  1
4  1

In [13]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [14]:
X.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      50      51      52      53      54      55      56  \
0  0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1  0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2  0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3  0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4  0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   

       57      58      59  
0  0.0084  0.0090  0.0032  
1  0.0049  0.0052  0.0044  
2  0.0164  0.0095  0.0078  
3  0.0044  0.0040  0.0117  
4  0.0048  0.0107  0.0094  

[5 rows x 60 columns]

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=5)

In [16]:
X_train.head()

0       1       2       3       4       5       6       7       8   \
50  0.0353  0.0713  0.0326  0.0272  0.0370  0.0792  0.1083  0.0687  0.0298   
55  0.0201  0.0116  0.0123  0.0245  0.0547  0.0208  0.0891  0.0836  0.1335   
77  0.0336  0.0294  0.0476  0.0539  0.0794  0.0804  0.1136  0.1228  0.1235   
23  0.0115  0.0150  0.0136  0.0076  0.0211  0.1058  0.1023  0.0440  0.0931   
45  0.0408  0.0653  0.0397  0.0604  0.0496  0.1817  0.1178  0.1024  0.0583   

        9   ...      50      51      52      53      54      55      56  \
50  0.0880  ...  0.0098  0.0163  0.0242  0.0043  0.0202  0.0108  0.0037   
55  0.1199  ...  0.0032  0.0076  0.0045  0.0056  0.0075  0.0037  0.0045   
77  0.0842  ...  0.0033  0.0150  0.0111  0.0032  0.0035  0.0169  0.0137   
23  0.0734  ...  0.0107  0.0091  0.0016  0.0084  0.0064  0.0026  0.0029   
45  0.2176  ...  0.0066  0.0062  0.0129  0.0184  0.0069  0.0198  0.0199   

        57      58      59  
50  0.0096  0.0093  0.0053  
55  0.0029  0.0008  0.0018  
77  0.0015  0.0069  0.0051  
23  0.0037  0.0070  0.0041  
45  0.0102  0.0070  0.0055  

[5 rows x 60 columns]

In [19]:
import tensorflow as tf
from tensorflow import keras

In [22]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim = 60, activation='relu'),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 4ms/step - loss: 0.6791 - accuracy: 0.6923
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6626 - accuracy: 0.7051
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6451 - accuracy: 0.6538
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6160 - accuracy: 0.6987
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5820 - accuracy: 0.7564
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5629 - accuracy: 0.7051
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5144 - accuracy: 0.7949
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4857 - accuracy: 0.7628
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4710 - accuracy: 0.8013
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4700 - accuracy: 0.7628
Epoch 11/

In [23]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 3ms/step - loss: 0.5599 - accuracy: 0.8462


[0.5598852634429932, 0.8461538553237915]

In [46]:
y_pred = model.predict(X_test).reshape(-1)
print(y_pred[:10])

y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 [==============================] - 0s 997us/step
[4.2401171e-06 6.8584192e-01 1.3878943e-02 2.7230110e-03 2.1190463e-01
 3.8233293e-06 9.5102286e-01 9.9999923e-01 1.1115571e-04 9.9996680e-01]
[0. 1. 0. 0. 0. 0. 1. 1. 0. 1.]


In [47]:
y_test[:10]

R
156  0
21   1
193  0
159  0
34   1
196  0
6    1
25   1
115  0
51   1

In [48]:
from sklearn.metrics import confusion_matrix, classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88        32
           1       0.83      0.75      0.79        20

    accuracy                           0.85        52
   macro avg       0.84      0.83      0.83        52
weighted avg       0.85      0.85      0.84        52



In [49]:
model_w_dropout = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation='sigmoid')
])

model_w_dropout.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model_w_dropout.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.7364 - accuracy: 0.5000
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7390 - accuracy: 0.4167
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7042 - accuracy: 0.4615
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5256
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6730 - accuracy: 0.5577
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7132 - accuracy: 0.4936
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6775 - accuracy: 0.5962
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6763 - accuracy: 0.5833
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6767 - accuracy: 0.5769
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6903 - accuracy: 0.5705
Epoch 11/

In [50]:
model_w_dropout.evaluate(X_test, y_test)

2/2 [==============================] - 0s 3ms/step - loss: 0.3251 - accuracy: 0.8846


[0.32506993412971497, 0.8846153616905212]

In [55]:
y_pred = model_w_dropout.predict(X_test).reshape(-1)
y_pred[:10]

2/2 [==============================] - 0s 3ms/step


array([0.0274197 , 0.66087997, 0.07580297, 0.16975474, 0.9353608 ,
       0.00595012, 0.85097885, 0.99748737, 0.22145486, 0.99592894],
      dtype=float32)

In [56]:
y_pred = np.round(y_pred)
y_pred[:10]

array([0., 1., 0., 0., 1., 0., 1., 1., 0., 1.], dtype=float32)

In [57]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.88      0.94      0.91        32
           1       0.89      0.80      0.84        20

    accuracy                           0.88        52
   macro avg       0.89      0.87      0.88        52
weighted avg       0.88      0.88      0.88        52

